[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone -b dev https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
GANALYTICS = "G-GXRDN10PHJ"
HOME_GRAPH = "y"
LANDING_BUTTON = "<span class='shake-rotate shake-freeze'>Have a look?</span>"
LANDING_DESCRIPTION = "<div>My physical brain is <div style='font-size: 4rem; display: inline-block' class='animate__animated animate__pulse animate__infinite'>ðŸ’¤ </div> but my digital brain is active.</div>"
LANDING_PAGE = "home"
LANDING_TITLE = "<span class='hvr-grow'>Hi I'm Peter</span>"
PAGE_GRAPH = "y"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ppeetteerrs/obsidian-pkm"
SITE_TITLE = "Peter's 2<sup>nd</sup> <span class='hvr-pulse'>ðŸ§ </span>"
SITE_TITLE_TAB = "Peter's Second ðŸ§ "
SITE_URL = "https://peteryuen.netlify.app/"
SLUGIFY = "y"
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
